[package]
name = "pyscemu"
version = "0.5.1"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html
[lib]
name = "pyscemu"
crate-type = ["cdylib"]

[dependencies]
pyo3 = "0.18.1"
libscemu = "0.15.1"
#libscemu = { path = "/home/sha0/src/libscemu/" }
